[package]
name = "pv-export"
description = "Video export for piano-viz"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
png.workspace = true
pv-audio.workspace = true
pv-core.workspace = true
pv-design.workspace = true
pv-render.workspace = true
thiserror.workspace = true

[dev-dependencies]
pv-midi.workspace = true

[lints]
workspace = true
