[package]
name = "pv-app"
description = "piano-viz desktop application"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "piano-viz"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
midir.workspace = true
notify.workspace = true
pollster.workspace = true
pv-audio.workspace = true
pv-core.workspace = true
pv-design.workspace = true
pv-export.workspace = true
pv-midi.workspace = true
pv-render.workspace = true
rfd.workspace = true
rtrb.workspace = true
winit.workspace = true

[lints]
workspace = true
